[package]
name = "pallet-stwo-verifier"
version = "0.1.0"
description = "A Stwo STARK verifier pallet"
homepage.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hp-verifiers = { workspace = true }
pallet-verifiers = { workspace = true }

codec = { workspace = true }
scale-info = { workspace = true }

frame-support = { workspace = true }
sp-core = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
native = { workspace = true }

# Cryptographic dependencies for real verification (no-std compatible)
ark-ff = { version = "0.4", default-features = false }
ark-ec = { version = "0.4", default-features = false }
ark-std = { version = "0.4", default-features = false }
ark-bn254 = { version = "0.4", default-features = false }
ark-pallas = { version = "0.4", default-features = false }
ark-vesta = { version = "0.4", default-features = false }
# Hash functions (no-std compatible)
sha2 = { version = "0.10", default-features = false }
blake2 = { version = "0.10", default-features = false }
# Serialization (no-std compatible)
serde = { version = "1.0", default-features = false, features = ["derive"] }
# Random number generation removed - not essential for STARK verification

[dev-dependencies]
rstest = { workspace = true }
rstest_reuse = { workspace = true }
hex-literal = { workspace = true }
pallet-balances = { workspace = true }
sp-io = { workspace = true, features = ["std"] }

[features]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"hp-verifiers/std",
	"native/std",
	"pallet-balances/std",
	"pallet-verifiers/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"ark-ff/std",
	"ark-ec/std",
	"ark-std/std",
	"ark-bn254/std",
	"ark-pallas/std",
	"ark-vesta/std",
	"sha2/std",
	"blake2/std",
	"serde/std",
]
default = [ "std" ]
runtime-benchmarks = [
	"dep:frame-benchmarking",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-verifiers/runtime-benchmarks",
]







