name: Verify Stwo Verifier

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install dependencies (protoc, wasm target)
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          rustup target add wasm32-unknown-unknown

      - name: Verify locked deps
        run: |
          cargo update -w --locked

      - name: Build and test Stwo components
        run: |
          cargo test -p zkv-stwo --lib --locked --verbose
          cargo test -p pallet-zkverify-starky --lib --locked --verbose

      - name: Workspace check (non-fatal)
        continue-on-error: true
        run: |
          cargo check --workspace --locked --verbose


